export const DEMO_SUMMARY = `
**Introduction to Aerodynamics
*Aerodynamics is the study of the motion of air, particularly when interacting with a solid object.
*Key concepts include lift, drag, thrust, and weight.
*Understanding airflow is crucial for designing aircraft and other vehicles.

**Principles of Flight
*Bernoulli's Principle: Faster moving air has lower pressure.
*Newton's Third Law: For every action, there is an equal and opposite reaction.
*Airfoils are shaped to create pressure differences, generating lift.

**Types of Drag
*Parasitic Drag: Caused by the shape of the object (form drag, skin friction drag, interference drag).
*Induced Drag: A byproduct of lift generation.
*Wave Drag: Occurs at transonic and supersonic speeds due to shockwaves.

**Aircraft Control Surfaces
*Ailerons: Control roll.
*Elevators: Control pitch.
*Rudder: Controls yaw.
*Flaps and Slats: Increase lift and drag for takeoff and landing.

**Supersonic Flight
*Mach Number: Ratio of object's speed to the speed of sound.
*Sound Barrier: The apparent physical boundary an aircraft exceeds when it goes supersonic.
*Shockwaves: Conical disturbances generated by objects traveling at supersonic speeds.
*Challenges include increased drag and aerodynamic heating.
`;